import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :food_truck_bot, FoodTruckBotWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

config :logger,
  level: String.to_atom(System.get_env("LOG_LEVEL") || "info"),
  metadata: :all

config :logger, :console,
  format: "$metadata[$level] $message\n",
  metadata: [:file, :line]

# https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/
# config :opentelemetry, :resource,
#   [
#     # In production service.name is set based on OS env vars from Erlang release
#     {"service.name", to_string(Mix.Project.config[:app])},
#     # {"service.namespace", "MyNamespace"},
#     {"service.version", Mix.Project.config[:version]},
#   ]

# https://hexdocs.pm/opentelemetry_exporter/1.0.0/readme.html
# Maybe OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:55680
config :opentelemetry, :processors,
  otel_batch_processor: %{
    exporter: {
      :opentelemetry_exporter,
      %{
        protocol: :grpc,
        endpoints: [
          # gRPC
          'http://localhost:4317'
          # HTTP
          # 'http://localhost:4318'
          # 'http://localhost:55681'
          # {:http, 'localhost', 4318, []}
        ]
        # headers: [{"x-honeycomb-dataset", "experiments"}]
      }
    }
  }

config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: FoodTruckBot.Finch

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
